// File generated by FlutterFire CLI & customized for num-info-app
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBltL-2Yj_-U0QrMiYP-5OrJSrBIBBGqVU',
    appId: '1:270154579169:web:40f94cacd3e26a97570ba0',
    messagingSenderId: '270154579169',
    projectId: 'num-info-app',
    authDomain: 'num-info-app.firebaseapp.com',
    storageBucket: 'num-info-app.firebasestorage.app',
    measurementId: 'G-54JJY9LV53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtYfXdcBadl2lIwnSWxboJSUwhII3dKfY',
    appId: '1:270154579169:android:481ba744f3d8e62d570ba0',
    messagingSenderId: '270154579169',
    projectId: 'num-info-app',
    storageBucket: 'num-info-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqQhcx09rTf0o5lr0_xBHHF9O5AilDRQM',
    appId: '1:270154579169:ios:c944baf4f4621ef7570ba0',
    messagingSenderId: '270154579169',
    projectId: 'num-info-app',
    storageBucket: 'num-info-app.firebasestorage.app',
    iosBundleId: 'com.example.infoApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqQhcx09rTf0o5lr0_xBHHF9O5AilDRQM',
    appId: '1:270154579169:ios:c944baf4f4621ef7570ba0',
    messagingSenderId: '270154579169',
    projectId: 'num-info-app',
    storageBucket: 'num-info-app.firebasestorage.app',
    iosBundleId: 'com.example.infoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBltL-2Yj_-U0QrMiYP-5OrJSrBIBBGqVU',
    appId: '1:270154579169:web:d0d431dad94cbbd6570ba0',
    messagingSenderId: '270154579169',
    projectId: 'num-info-app',
    authDomain: 'num-info-app.firebaseapp.com',
    storageBucket: 'num-info-app.firebasestorage.app',
    measurementId: 'G-RV3TS3ZPHH',
  );
}
